name: Commit Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '20.17.0'
  PNPM_VERSION: '8.15.4'

jobs:
  commit-lint:
    name: 🔍 Lint Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔍 Lint commits
        run:
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to
          ${{ github.event.pull_request.head.sha }} --verbose
